int GroupsGet(LPCSTR name, ConGroup* group);
int ClientsUserInfo(const int login, UserRecord* inf);
int HistoryPrices(LPCSTR symbol, double* prices, time_t* ctm, int* dir);
void LogsOut(const int code, LPCSTR ip, LPCSTR msg);
int OrdersClose(const TradeTransInfo* trans, UserInfo* user);
int OrdersGet(const int ticket, TradeRecord* order);
TradeRecord* OrdersGet(const time_t from, const time_t to, const int* logins, const int count, int* total);
int OrdersUpdate(TradeRecord* order, UserInfo* user, const int mode);
int RequestsConfirmPrice(const int id, const UserInfo* us, double price, double* prices);
int RequestsFree(const int id, const int manager);
int RequestsLock(const int id, const int manager);
int RequestsReset(const int id, const UserInfo* us, const char flag);
int SymbolsGet(LPCSTR symbol, ConSymbol* security);
double TradesCalcConvertation(LPCSTR group, const int margin_mode, const double price, const ConSymbol* symbol);
int TradesCalcProfit(LPCSTR group, TradeRecord* tpi);
int TradesCheckSessions(const ConSymbol* symbol, const time_t ctm);
void TradesCommission(TradeRecord* trade, LPCSTR group, const ConSymbol* symbol);
int TradesMarginInfo(UserInfo* user, double* margin, double* freemargin, double* equity);
time_t TradeTime(void);
void CommonGet(ConCommon* info);