 void MtSrvAbout(testA* info) override final;
 int MtSrvStartup() override final;
 void MtSrvCleanup() override final;
 int MtSrvPluginCfgAdd(const testA* cfg) override final;
 int MtSrvPluginCfgSet(const testA* values, const int total) override final;
 int MtSrvPluginCfgDelete(LPCSTR name) override final;
 int MtSrvPluginCfgGet(LPCSTR name, testA* cfg) override final;
 int MtSrvPluginCfgNext(const int index, testA* cfg) override final;
 int MtSrvPluginCfgTotal() override final;
 void MtSrvTradeRequestApply(testA* request, const int isdemo) override final;
 int MtSrvTradeStopsFilter(const testA* group, const testA* symbol, const testA* trade ) override final;
 int MtSrvTradeStopsApply(const testA* user, const testA* group, const testA* symbol, testA* trade, const int isTP ) override final;
 int MtSrvTradePendingsFilter(const testA* group, const testA* symbol, const testA* trade ) override final;
 int MtSrvTradePendingsApply(const testA* user, const testA* group, const testA* symbol, const testA* pending, testA* trade ) override final;
 int MtSrvTradeStopoutsFilter(const testA* group, const testA* symbol, const int login, const double equity, const double margin ) override final;
 int MtSrvTradeStopoutsApply(const testA* user, const testA* group, const testA* symbol, testA* stopout ) override final;
 void MtSrvTradesAddRequest(testA* trade, const testA* request, const testA* user, const testA* symbol, const int mode ) override final;
 int MtSrvTradeTransaction(testA* trade, testA* user, testA* request_id) override final;
 void MtSrvTradeCommission(testA* trade, const testA* Sec, const testA* Grp ) override final;
 int MtSrvTradeCommissionAgent(testA* trade, const testA* sec, const testA* info ) override final;
 void MtSrvHistoryTickApply(const testA* symbol, testA* inf) override final;
