 void MtSrvAbout(PluginInfo* info) override final;
 int MtSrvStartup() override final;
 void MtSrvCleanup() override final;
 int MtSrvPluginCfgAdd(const PluginCfg* cfg) override final;
 int MtSrvPluginCfgSet(const PluginCfg* values, const int total) override final;
 int MtSrvPluginCfgDelete(LPCSTR name) override final;
 int MtSrvPluginCfgGet(LPCSTR name, PluginCfg* cfg) override final;
 int MtSrvPluginCfgNext(const int index, PluginCfg* cfg) override final;
 int MtSrvPluginCfgTotal() override final;
 void MtSrvTradeRequestApply(RequestInfo* request, const int isdemo) override final;
 int MtSrvTradeStopsFilter(const ConGroup* group, const ConSymbol* symbol, const TradeRecord* trade ) override final;
 int MtSrvTradeStopsApply(const UserInfo* user, const ConGroup* group, const ConSymbol* symbol, TradeRecord* trade, const int isTP ) override final;
 int MtSrvTradePendingsFilter(const ConGroup* group, const ConSymbol* symbol, const TradeRecord* trade ) override final;
 int MtSrvTradePendingsApply(const UserInfo* user, const ConGroup* group, const ConSymbol* symbol, const TradeRecord* pending, TradeRecord* trade ) override final;
 int MtSrvTradeStopoutsFilter(const ConGroup* group, const ConSymbol* symbol, const int login, const double equity, const double margin ) override final;
 int MtSrvTradeStopoutsApply(const UserInfo* user, const ConGroup* group, const ConSymbol* symbol, TradeRecord* stopout ) override final;
 void MtSrvTradesAddRequest(TradeRecord* trade, const RequestInfo* request, const UserInfo* user, const ConSymbol* symbol, const int mode ) override final;
 int MtSrvTradeTransaction(TradeTransInfo* trade, UserInfo* user, int* request_id) override final;
 void MtSrvTradeCommission(TradeRecord* trade, const ConSymbol* Sec, const ConGroup* Grp ) override final;
 int MtSrvTradeCommissionAgent(TradeRecord* trade, const ConSymbol* sec, const UserInfo* info ) override final;
 void MtSrvHistoryTickApply(const ConSymbol* symbol, FeedTick* inf) override final;
